### ISSUE TITLE
Suggestion for improvement: True retention.

### ISSUE THREAD

**Issue by cjdduarte** [glfharris/Syllabus#6]
I have a true average retention between 89% and 95%.
But for the deck below, I have a true retention of 75%.

It would be interesting to see these 3 columns in your addon.

![image](https://user-images.githubusercontent.com/42243532/47258397-f82e2700-d470-11e8-9054-d4a958f3b6a6.png)

![image](https://user-images.githubusercontent.com/42243532/47258435-725eab80-d471-11e8-837e-4ddf22febd60.png)

**Comment by cjdduarte** [comment]
hello?

**Comment by cjdduarte** [comment]
Excuse me. I saw you implemented

**Comment by glfharris** [comment]
Hey!

Yeah I have some retention metrics implemented now. At the moment they're all total over the life of the cards, and not looking at any shorter span.

I'm in a few minds about it. Essentially because the review time for mature cards is >21 days, I don't think retention over the last 24h tells you much, as it's more likely a function of the specific cards you saw on that day vs how good you are in that subject.

I think last month might be useful, as then you could tell if there's been any improvement over that month vs base line.

**Comment by cjdduarte** [comment]
> I think last month might be useful, as then you could tell if there's been any improvement over that month vs base line.

I agree.
